### ISSUE TITLE
[1.16.5] No way to remove stages

### ISSUE THREAD

**Issue by conneich** [Darkhax-Minecraft/ItemStages#64]
It doesn't appear there are any ways to currently replace or remove stages from items.

I was trying to hide all items in a mod during start up and then changing the stage to another afterward but it seems to only add stages instead of replacing like I thought it would. This was done with hiding the mod before and after adding another stage to a singular item.

**Comment by Darkhax** [comment]
That is correct, intentional. When you stage an item using one of the helper methods it creates a rule that checks items on a case by case basis. This rule does not have a predetermined context of every item or ItemStack that would match it's test so exceptions can not be added and specific items can not be removed. You must be 100% sure you want to stage something before you stage it. 

The recommended way to do what you would like to do is through item tags. Create a new tag for your stage and then add/remove the items individually from that tag. This can be done using loops to add all items from a specific modid except for the ones you want.
