### ISSUE TITLE
[BUG] restrict is not working with tag "Damage"

### ISSUE THREAD

**Issue by h0sk1** [Darkhax-Minecraft/ItemStages#96]
### Minecraft Version

1.19.2

### Mod Version

5.1.4

### Mod Loader

Forge

### What environment are you running the mod in?

Dedicated Server

### Issue Description

Function "restrict" is not working with damaged items. Could it be that tag "Damage" depends seperately from other tags?

![HWOaEtf5PKA](https://github.com/user-attachments/assets/dc2dc133-20a9-4fb2-b9a6-fe77e945c67c)

![ega8RmOC00w](https://github.com/user-attachments/assets/ea052148-bc50-453d-b74d-2c771ca0387a)

**Damaged diamond sword has tag "Damage". It ignored by the function "restrict"**

![y0aTgjok5ZQ](https://github.com/user-attachments/assets/7425b3de-56e6-4e83-b2f7-0a2a882dc4d6)

**Comment by Darkhax** [comment]
Hello, can you please include the script that you are using to create this restriction?

**Comment by h0sk1** [comment]
> Hello, can you please include the script that you are using to create this restriction?

Yes. of course!

[Stages.txt](https://github.com/user-attachments/files/16236508/Stages.txt)

I ve changed the file format, because i cant attach file with format .zs

**Comment by Darkhax** [comment]
@h0sk1 Sorry it took me a bit to look at this. There are a few issues with your script.

1) You have `minercraft` instead of `minecraft` in that script. Not sure if that's intentional or not, but I changed it to `minecraft` in my script so I could test it with vanilla. 

2) CraftTweaker ingredients are damage sensitive by default so your script is only matching the default damage state. You can use the [`anyDamage`](https://docs.blamejared.com/1.19/en/vanilla/api/ingredient/IIngredient#anyDamage) method to accept any damage value.

Here is a working script where the diamond sword acts like your example, and the golden sword works with any damage value.
```zenscript
import mods.itemstages.ItemStages;

ItemStages.restrict(<item:minecraft:diamond_sword>, "one").preventPickup(false).preventInventory(false);
ItemStages.restrict(<item:minecraft:golden_sword>.anyDamage(), "two").preventPickup(false).preventInventory(false);
```

**Comment by h0sk1** [comment]
@Darkhax I just didnt find it in the documentation for the mod. It s working! Thanks for the help!
